apiVersion: v1
kind: Service
metadata:
  name: quarkus-app
  labels:
    app: quarkus-app
spec:
  selector:
    app: quarkus-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
