---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.9.2
    app.quarkus.io/commit-id: 9c68c974334061c01ebf4b5f9b8d7d57006dc140
    app.quarkus.io/vcs-uri: https://github.com/eduardoajs2020/quarkus-devsecops.git
    app.quarkus.io/build-timestamp: 2025-08-25 - 05:07:01 +0000
  labels:
    app.kubernetes.io/name: quarkus-app
    app.kubernetes.io/version: 1.0.0
    app: quarkus-app
    app.kubernetes.io/managed-by: quarkus
  name: quarkus-app
  namespace: quarkus-dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-app
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.9.2
    app.quarkus.io/commit-id: 9c68c974334061c01ebf4b5f9b8d7d57006dc140
    app.quarkus.io/vcs-uri: https://github.com/eduardoajs2020/quarkus-devsecops.git
    app.quarkus.io/build-timestamp: 2025-08-25 - 05:07:01 +0000
  labels:
    app.kubernetes.io/name: quarkus-app
    app.kubernetes.io/version: 1.0.0
    app: quarkus-app
    app.kubernetes.io/managed-by: quarkus
  name: quarkus-app
  namespace: quarkus-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-app
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.9.2
        app.quarkus.io/commit-id: 9c68c974334061c01ebf4b5f9b8d7d57006dc140
        app.quarkus.io/vcs-uri: https://github.com/eduardoajs2020/quarkus-devsecops.git
        app.quarkus.io/build-timestamp: 2025-08-25 - 05:07:01 +0000
      labels:
        app: quarkus-app
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: quarkus-app
        app.kubernetes.io/version: 1.0.0
      namespace: quarkus-dev
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/eduardoajs2020/quarkus-app:1.0.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: quarkus-app
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
