apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quarkus-role
  namespace: quarkus-dev
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch", "update"]