    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

    - name: Debug GitHub Token
      run: |
        echo "Testando autenticação com GitHub API..."
        curl -H "Authorization: token ${{ secrets.GH_PATH }}" https://api.github.com/user

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PATH }}
    